export const DELAY_LOADING = 1000

export const DURATION_FIRST_ANIMATION = 2000
export const DURATION_SECOND_ANIMATION = 1200
export const DURATION_THIRD_ANIMATION = 500

export const DELAY_SECOND_ANIMATION = DURATION_FIRST_ANIMATION + DELAY_LOADING
export const DELAY_THIRD_ANIMATION = DELAY_SECOND_ANIMATION + DURATION_SECOND_ANIMATION
    // export const DELAY_FOURTH_ANIMATION = DELAY_THIRD_ANIMATION + 500